apiVersion: automation.cloudbees.io/v1alpha1
kind: Workflow
name: reusable

on:
  workflow_call: {}

metadata:
  stages/v1alpha1:
    - name: stage-2
      jobs: [deep-rw-job-1, deep-rw-job-2]

jobs:
  deep-rw-job-1:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "hello rw-job-1"
  deep-rw-job-2:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "hello rw-job-2"