apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: release

on:
  push:
    branches:
    - '**'
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

metadata:
  stages/v1alpha1:
    - name: stage-1
      jobs: [job-1, job-2, job-3]
    - name: stage-2
      jobs: [job-4, job-5, job-6]
    - name: stage-3
      jobs: [job-7, job-8]
    - name: stage-4
      jobs: [job-9, job-10]

jobs:
  # stage-1
  job-1:
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-1"
  job-2:
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-2"
  job-3:
    needs: [job-2, job-1]
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-3"

  # stage-2
  job-4:
    needs: job-3
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-4"
  job-5:
    needs: job-3
    uses: ./reusable/reusable.yaml

  job-6:
    needs: [job-5, job-4]
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-6"

  # stage-3
  job-7:
    needs: job-6
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-7"
  job-8:
    needs: job-6
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-8"

  # stage-4
  job-9:
    needs: [job-7, job-8]
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-9"
  job-10:
    needs: job-9
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-10"
